version: '3.8'
services:
  redis:
    image: redis:8.0
    container_name: redis
    restart: always
    env_file:
      - .env.prod.properties
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: sh -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    networks:
      - mixchat-network

  redis-init:
    image: redis:8.0
    depends_on:
      - redis
    env_file:
      - .env.prod.properties
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    entrypoint: >
      sh -c "sleep 5 && cat /init.redis | redis-cli -h redis -a ${REDIS_PASSWORD} --no-auth-warning"
    volumes:
      - ./docker/config/redis/init.redis:/init.redis
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$$REDIS_PASSWORD\" ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    env_file:
      - .env.prod.properties
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./docker/config/mongo/schema.js:/docker-entrypoint-initdb.d/schema.js
      - ./docker/config/mongo/init.js:/docker-entrypoint-initdb.d/init.js
    networks:
      - mixchat-network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.11.1
    container_name: nginx-proxy-manager
    restart: always
    env_file:
      - .env.prod.properties
    environment:
      DISABLE_IPV6: 'true'
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - mixchat-network

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local

networks:
  mixchat-network:
    driver: bridge