jwt:
  access-token-expiration-seconds: "#{60 * 120}"
  refresh-token-expiration-seconds: "#{60 * 60 * 24 * 7}"
redis:
  prefix:
    refresh-token: "refresh:"
cookie:
  domain: ${DOMAIN_NAME:mixchat.shop}
member:
  default-image-name: "default-profile.webp"
notification:
  retention-days: 30